steps:
  - name: debian:bullseye-slim
    id: Download, Install, and Build
    dir: /workspace
    entrypoint: bash
    args:
      - -c
      - |
        apt-get update && apt-get install -y curl unzip && \

        curl -L -o bun-install.sh https://bun.sh/install && \
        chmod +x bun-install.sh && \
        ./bun-install.sh && \
        ~/.bun/bin/bun install && \

        curl -L -o encore-install.sh https://encore.dev/install.sh && \
        chmod +x encore-install.sh && \
        ./encore-install.sh && \
        ln -s /builder/home/.encore/bin/encore /usr/local/bin/encore && \
        encore telemetry disable && \

        encore build docker --base=oven/bun:slim $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  REPO_NAME: encore-oauth-server
  _TRIGGER_ID: be2a2212-afbb-4180-925a-051564dfc8b5
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _PLATFORM: managed
  _SERVICE_NAME: server
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - encore-oauth-server
